### ISSUE TITLE
Fast forward, rewind and the timeline do not work

### ISSUE THREAD

**Issue by Jak0busus** [FoofooTheGuy/VidInjector9000#1]
I have a film which I created through the VidInjector9001. The film is about 2 hours long. However, the total length is not displayed, which is why fast-forwarding does not work. 

![grafik](https://github.com/FoofooTheGuy/VidInjector9000/assets/57959862/4bf07aa0-09f8-4ab8-9271-186987ce91bd)

**Comment by FoofooTheGuy** [comment]
This is a problem with the moflex file. Mobiclip Multicore Encoder (let's call it MME) probably crashed half way through the encode

try one of these:
- re encode the input video file
- encode to avi with MME and use that avi as input for encoding moflex
