### ISSUE TITLE
Question instead of issue

### ISSUE THREAD

**Issue by LittleTale** [FoofooTheGuy/VidInjector9000#2]
Simple question, does this support 3D video files and so how to encode ?
thanks

**Comment by FoofooTheGuy** [comment]
Yes, as the [common questions type of section](https://github.com/FoofooTheGuy/VidInjector9000#you-may-ask) part in the readme says, you can use the program _Mobiclip Multicore Encoder_ to create .moflex files.

**Comment by LittleTale** [comment]
Thanks, I read the FAQ but I didn't know about .moflex existence and its ability to convert 3D ! Thanks a lot for the amazing Homebrew
